### PR TITLE
German translation ready for acceptance 

### PR DESCRIPTION
**Pull request by herold74**

### CODE REVIEW

**Comment by rh-it-decisions** [comment]
This is wonderful, thank you both!

**Comment by ruhbehka** [comment]
This is wonderful, thank you for the translation!

**Comment by joschro** [comment]
Hi all,

Guenter and I would love to generate the other document formats as well but wonder how the conversion into PDF and ODP takes place? Is this a manual copy&paste job?

cheers,
Jos

**Comment by rh-it-decisions** [comment]
Yes, I'm afraid so!

**Pull request merged**
